spring: 
    profiles:
        active:
        - dev
---
spring:
    profiles: dev
    application:
        name: demo-config-dev
---
spring:
    profiles: test
    application:
        name: demo-config-test